export const imagePrompts = {
  magpiePortrait:
    "High-quality cartoon editorial portrait of Justice Magpie, an elderly British magpie judge, stern and exhausted, wearing a simple barrister wig and small spectacles. Old English law library, cream paper wall, dark ink shelves, oxblood leather chair, brass trim. Premium hand-painted cartoon editorial illustration, crisp raster art, ink and gouache texture, magazine spot illustration quality. Centered square portrait, shoulders up, no text, no logo, no 3D, no neon, no crypto symbols, no Lady Justice, no scales, no gavel.",
  courtHero:
    "High-quality cartoon editorial illustration of an old English law library courtroom where an elderly British magpie judge presides, shabby but dignified, funny and polished. Tall dark-ink law shelves, cream paper walls, brass plaque details, oxblood leather books, a dusty wooden clerk desk, scattered receipts and case papers, a Wi-Fi router subtly tucked on a shelf. Wide 16:9 cinematic scene, generous readable negative space on the left for headline text, character and bench on right third. Cream, oxblood, ink, brass, moss palette. No text, no logos, no crypto coins, no robots, no Lady Justice, no scales, no gavel, no 3D, no stock courthouse, no watermark.",
  evidenceCollage:
    "High-quality cartoon editorial illustration of petty courtroom evidence: crumpled receipts, typed complaint slips, wax seals, brass paper clips, an ink bottle, a fountain pen, and two small verdict cards on a wooden law library desk. Old English law library desk surface, cream papers, oxblood folders, brass desk objects. Landscape 4:3 composition with object cluster and usable negative space. No readable words, no logos, no crypto coins, no robots, no Lady Justice, no scales, no gavel, no 3D, no watermark.",
  verdictCardsBackground:
    "High-quality cartoon editorial illustration of two physical verdict cards sliding across a law library desk, one dignified green-accent acquittal card and one oxblood sentence card, with wax seals and brass edges, no readable text. Close view of cream paper cards on dark wood, ink stains, brass trim, old legal ledger texture. Wide horizontal image, cards centered lower half, open space above for verdict text overlays. No logos, no crypto coins, no robots, no Lady Justice, no scales, no gavel, no 3D, no watermark.",
  courtLibraryBackground:
    "A subtle old English law library interior, cream paper tones, dark ink shelves, brass details, oxblood accents, slightly shabby but dignified, editorial illustration style, very low contrast, designed as a website background, no people, no text, no logos, no crypto symbols, no 3D, no neon."
};
